const $=id=>document.getElementById(id),key="parangbird-wardrobe-v2";let wardrobe=JSON.parse(localStorage.getItem(key)||"[]");
const cool=new Set(["blue","navy","black","white","gray"]),warm=new Set(["beige","khaki","olive","red"]);
const em={blue:"💙",navy:"🔵",black:"🖤",white:"🤍",gray:"🩶",beige:"🤎",khaki:"🫒",olive:"🫒",red:"❤️"};
function save(){localStorage.setItem(key,JSON.stringify(wardrobe));render()}
function render(){const b=$("wardrobe");b.innerHTML=wardrobe.length?wardrobe.map((x,i)=>`<div class="item"><button class="x" onclick="removeItem(${i})">×</button><strong>${em[x.color]||"🎨"} ${x.name}</strong><small>${x.category}</small></div>`).join(""):'<p class="muted">아직 등록된 옷이 없습니다.</p>'}
window.removeItem=i=>{wardrobe.splice(i,1);save()}
$("wardrobeForm").onsubmit=e=>{e.preventDefault();wardrobe.push({name:$("name").value.trim(),category:$("category").value,color:$("color").value});e.target.reset();save()}
$("clearBtn").onclick=()=>{wardrobe=[];save();$("looks").className="looks empty";$("looks").textContent="옷장을 등록하고 추천 버튼을 눌러보세요."}
$("demoBtn").onclick=()=>{wardrobe=[{name:"파란색 반팔티",category:"상의",color:"blue"},{name:"블랙 팬츠",category:"하의",color:"black"},{name:"카키 팬츠",category:"하의",color:"khaki"},{name:"네이비 셔츠",category:"상의",color:"navy"},{name:"검정 운동화",category:"신발",color:"black"},{name:"검정 모자",category:"모자",color:"black"},{name:"선글라스",category:"액세서리",color:"black"}];save()}
function pick(cat,cs){return wardrobe.find(x=>x.category===cat&&(!cs||cs.includes(x.color)))||wardrobe.find(x=>x.category===cat)}
$("recommendBtn").onclick=()=>{let tone=$("tone").value;let top=pick("상의",tone==="cool"?["blue","navy","white","gray"]:["white","beige","olive"]);let bot=pick("하의",["black","navy","gray"]);let kh=pick("하의",["khaki","olive","beige"]);let shoe=pick("신발",["black","white","gray"]);let cap=pick("모자",["black","navy"]);let acc=pick("액세서리",["black","gray"]);let arr=[["LOOK 1 · 깔끔한 기본",[top,bot,shoe,cap],"쿨톤 상의와 블랙을 연결해 색상 대비를 또렷하게 정리했습니다."],["LOOK 2 · 트렌디 캐주얼",[top,kh,shoe,acc],"차가운 상의에 카키를 섞어 단조로움을 줄이고 얼굴 주변은 쿨톤으로 유지했습니다."],["LOOK 3 · 레트로 스포츠",[pick("상의",["white","navy","blue"]),bot,shoe,cap],"화이트·네이비·블랙 대비로 올드스쿨 스포츠 무드를 현대적으로 구성했습니다."]];$("looks").className="looks";$("looks").innerHTML=arr.map((l,i)=>{let a=l[1].filter(Boolean),score=Math.min(98,82+i*4+(tone==="cool"?5:0));return `<article class="look"><span class="badge">🐦 파랑새 추천</span><h3>${l[0]}</h3><div class="score">${score}%</div><div class="muted">현재 컬러 프로필 기준</div><ul>${a.map(x=>`<li>${em[x.color]||"🎨"} ${x.name}</li>`).join("")}</ul><p class="why">${l[2]}</p></article>`}).join("")}
render();